# Site settings
title: Daryl - Ryan's Daryl
tagline: We'll figure it out later
email: ryan.letson@gmail.com
description: > # this means to ignore newlines until "baseurl"
  I'm going to make this site whatever I want it to be. Could be a site about Rolex watches, Cervelo
  bicycles, or running in the Dopey Challenge'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ryan.letson.name" # the base hostname & protocol for your site
twitter_username: r_letson
github_username:  rletson
paginate: 5

# Build settings
markdown: kramdown
highlighter: pygments

# Gems
gems: [jekyll-paginate]